# Copyright 2018 Stefan Seefeld
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)
language: cpp

sudo: false

branches:
  only:
    - master
    - develop
    - doc
    - ci
    - opencl

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    # Khronos OpenCL ICD
    - OPENCL_REGISTRY=https://www.khronos.org/registry/cl
    - OPENCL_ROOT=${DEPS_DIR}/opencl
    # POCL
    - POCL_BRANCH=release_0_13 # branch/tag
    #- POCL_COMMIT= # commit id
    - POCL_LLVM_VERSION=3.8.0
    - POCL_LLVM_CONFIG=${DEPS_DIR}/llvm-${POCL_LLVM_VERSION}/bin/llvm-config
    - POCL_CXX_COMPILER=${DEPS_DIR}/llvm-${POCL_LLVM_VERSION}/bin/clang++
    - POCL_C_COMPILER=${DEPS_DIR}/llvm-${POCL_LLVM_VERSION}/bin/clang
  

matrix:
  include:
    - os: linux
      env:
      - LINUX_DIST=trusty
      - TOOLSET=gcc
      - COMPILER=g++-7
      - CXXSTD=c++11
      - OPENCL_LIB=pocl
      #- OPENCL_LIB=amdappsdk
      #- OPENCL_HEADERS_VER="21"
      #- AMDAPPSDK_VERSION=300 # OpenCL 2.0
      - ENV_CXX_FLAGS="-DBOOST_COMPUTE_MAX_CL_VERSION=200"
      addons:
        apt:
          packages:
            - g++-7
            - libhwloc-dev
          sources:
            - ubuntu-toolchain-r-test

    #- os: osx
    #  env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++11


before_install:
    # Install dependencies
    - |
      # POCL dependencies for Trusty
      # llvm-toolchain-trusty-3.7 is not whitelisted yet https://github.com/travis-ci/apt-source-whitelist/issues/199
      if [[ ${LINUX_DIST} == "trusty" && ${OPENCL_LIB} == "pocl" ]]; then
        # see https://github.com/travis-ci/travis-ci/issues/6120
        POCL_LLVM_URL=http://llvm.org/releases/${POCL_LLVM_VERSION}/clang+llvm-${POCL_LLVM_VERSION}-x86_64-linux-gnu-ubuntu-14.04.tar.xz
        mkdir -p ${DEPS_DIR}/llvm-${POCL_LLVM_VERSION}
        travis_retry wget --no-check-certificate --quiet -O llvm-${POCL_LLVM_VERSION}.tar.xz ${POCL_LLVM_URL}
        tar xf llvm-${POCL_LLVM_VERSION}.tar.xz -C ${DEPS_DIR}/llvm-${POCL_LLVM_VERSION} --strip-components 1

        #sudo add-apt-repository -y "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.7 main"
        #travis_retry wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | travis_retry sudo apt-key add -
        #sudo apt-get update -qq -
        #sudo apt-get install -qq -y clang-3.7 libclang-common-3.7-dev libclang-3.7-dev libclang1-3.7 libllvm3.7 lldb-3.7 llvm-3.7 llvm-3.7-dev llvm-3.7-runtime clang-modernize-3.7 clang-format-3.7 lldb-3.7-dev
      # OSX
      elif [[ ${TRAVIS_OS_NAME} == "osx" ]]; then
        brew update
        /usr/bin/yes | pip uninstall numpy
        brew outdated boost || brew upgrade boost
        brew outdated cmake || brew upgrade cmake
        brew install lcov homebrew/science/opencv
      fi
    ############################################################################
    # Build and install POCL https://github.com/pocl/pocl
    ############################################################################
    - |
      if [[ ${TRAVIS_OS_NAME} == "linux" && ${OPENCL_LIB} == "pocl" ]]; then
        travis_retry git clone --depth 1 https://github.com/pocl/pocl.git -b ${POCL_BRANCH}
        cd pocl
        if [[ -n "${POCL_COMMIT}" ]]; then
          git checkout ${POCL_COMMIT}
        fi
        mkdir build
        cd build
        cmake -DDIRECT_LINKAGE=ON -DENABLE_ICD=OFF -DCMAKE_C_COMPILER=${POCL_C_COMPILER} -DCMAKE_CXX_COMPILER=${POCL_CXX_COMPILER} -DWITH_LLVM_CONFIG=${POCL_LLVM_CONFIG} -DCMAKE_INSTALL_PREFIX=${OPENCL_ROOT}/pocl/ ..
        make install
        cd ../..
      fi



install:
  - cd ..
  - git clone -b master --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/build
  - git submodule update --init libs/config
  - git submodule update --init tools/boostdep
  - mkdir -p libs/numeric/
  - cp -r $TRAVIS_BUILD_DIR/* libs/numeric/ublas
  - python tools/boostdep/depinst/depinst.py numeric/ublas
  - ./bootstrap.sh
  - ./b2 headers

script:
  - |-
    echo "using $TOOLSET : : $COMPILER : <cxxflags>-std=$CXXSTD ;" > ~/user-config.jam
  - ./b2 libs/numeric/ublas/test toolset=$TOOLSET

notifications:
  email:
    on_success: always
